-- Typed models for the KokkaiKaigirokuApi SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Meeting
---@field closing? boolean
---@field date? string
---@field imageKind? string
---@field issue? string
---@field issueID? string
---@field meetingURL? string
---@field nameOfHouse? string
---@field nameOfMeeting? string
---@field pdfURL? string
---@field searchObject? string
---@field session? number
---@field speechRecord? table

---@class MeetingListMatch
---@field closing? boolean
---@field date? string
---@field imageKind? string
---@field issue? string
---@field issueID? string
---@field meetingURL? string
---@field nameOfHouse? string
---@field nameOfMeeting? string
---@field pdfURL? string
---@field searchObject? string
---@field session? number
---@field speechRecord? table

---@class MeetingList
---@field closing? boolean
---@field date? string
---@field imageKind? string
---@field issue? string
---@field issueID? string
---@field meetingURL? string
---@field nameOfHouse? string
---@field nameOfMeeting? string
---@field pdfURL? string
---@field searchObject? string
---@field session? number
---@field speechRecord? table

---@class MeetingListListMatch
---@field closing? boolean
---@field date? string
---@field imageKind? string
---@field issue? string
---@field issueID? string
---@field meetingURL? string
---@field nameOfHouse? string
---@field nameOfMeeting? string
---@field pdfURL? string
---@field searchObject? string
---@field session? number
---@field speechRecord? table

---@class Speech
---@field closing? boolean
---@field date? string
---@field imageKind? string
---@field issue? string
---@field issueID? string
---@field meetingURL? string
---@field nameOfHouse? string
---@field nameOfMeeting? string
---@field pdfURL? string
---@field searchObject? string
---@field session? number
---@field speaker? string
---@field speakerGroup? string
---@field speakerPosition? string
---@field speakerRole? string
---@field speakerYomi? string
---@field speech? string
---@field speechID? string
---@field speechOrder? number
---@field speechURL? string
---@field startPage? number

---@class SpeechListMatch
---@field closing? boolean
---@field date? string
---@field imageKind? string
---@field issue? string
---@field issueID? string
---@field meetingURL? string
---@field nameOfHouse? string
---@field nameOfMeeting? string
---@field pdfURL? string
---@field searchObject? string
---@field session? number
---@field speaker? string
---@field speakerGroup? string
---@field speakerPosition? string
---@field speakerRole? string
---@field speakerYomi? string
---@field speech? string
---@field speechID? string
---@field speechOrder? number
---@field speechURL? string
---@field startPage? number

local M = {}

return M
